language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  - DEPENDENCIES=
  - DEPENDENCIES=--prefer-lowest

install:
  composer update --no-interaction --prefer-stable --prefer-dist $DEPENDENCIES

script: vendor/bin/phpunit

stages:
  - Validate composer.json
  - Code Quality
  - Test

jobs:
  allow_failures:
    -   php: nightly

  include:
    -   stage: Code Quality
    -   name: PHPStan
        php: 7.2
        script: vendor/bin/phpstan analyse
    -   stage: Test
    -   name: Coverage
        php: 7.2
        before_script:
            - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
            - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
        script:
            - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
        after_script:
            - wget https://github.com/scrutinizer-ci/ocular/releases/download/1.5.2/ocular.phar
            - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

